server:
  port: 8200

spring:
  application:
    name: sys-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytieba?useUnicode=true & characterEncoding=utf-8 &
      useSSL=true & serverTimezone=Asia/Shanghai
    username: root
    password: Zjj714705217&

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zeng.sys.entity
  configuration:
    map-underscore-to-camel-case: true